<?php

/**
 * Implements hook_menu().
 */
function expedited_article_delivery_menu() {
  $items = array();

  $items['admin/config/services/expedited_article_delivery'] = array(
    'title' => 'Expedited Article Delivery',
    'description' => 'Configure settings for Expedited Article Delivery.',
    'access arguments' => array('administer expedited article delivery'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('expedited_article_delivery_admin_form'),
    'file' => 'includes/admin.form.inc',
  );

  $items['expedited_article_delivery/order'] = array (
    'page callback' => 'expedited_article_delivery_order_responder',
    'access callback' => TRUE,
  );

  $items['expedited_article_delivery/error'] = array (
    'page callback' => 'expedited_article_delivery_error',
    'access callback' => TRUE,
  );

  $items['expedited_article_delivery/success'] = array (
    'page callback' => 'expedited_article_delivery_success',
    'access callback' => TRUE,
  );
  
  return $items;
}


/**
 * Implements hook_permission().
 */
function expedited_article_delivery_permission() {
  return array(
    'administer expedited article delivery' => array(
      'title' => 'Administer Expedited Article Delivery',
      'description' => 'Manage the configuration of the Expedited Article Delivery module',
    ),
  );
}

/**
 * Callback functions
 */
function expedited_article_delivery_order_responder() {
  module_load_include('inc', 'expedited_article_delivery', 'includes/utilities');
  expedited_article_delivery_order_processor($_GET);
}

function expedited_article_delivery_error() {
  $content = theme('expedited_article_delivery_error_page');
  return $content;
}

function expedited_article_delivery_success() {
  $content = theme('expedited_article_delivery_success_page');
  return $content;
}

/**
 * Implements hook_theme(). 
 */
function expedited_article_delivery_theme() {
  return array(
    'expedited_article_delivery_error_page' => array(
      'path' => drupal_get_path('module', 'expedited_article_delivery').'/theme',
      'template' => 'expedited-article-delivery-error-page', //see expedited-article-delivery-error-page.tpl.php
    ),
    'expedited_article_delivery_success_page' => array(
      'path' => drupal_get_path('module', 'expedited_article_delivery').'/theme',
      'template' => 'expedited-article-delivery-success-page', //see expedited-article-delivery-success-page.tpl.php
    ),
  );
}

/**
 * Preprocess variables to be passed to the error page template assigned above in hook_theme().
 */
function template_preprocess_expedited_article_delivery_error_page(&$variables) {
  switch ($_GET['reason']) {
    case 'incomplete_data':
      $variables['error_message'] = variable_get('expedited_article_delivery_error_availability');
      break;
    case 'missing_roles':
      $variables['error_message'] = variable_get('expedited_article_delivery_error_login');
      break;
    default:
      $variables['error_message'] = variable_get('expedited_article_delivery_error_reprints');
  } 
  
  // Create ILL Link
  $open_url = '';
  $ill_link = variable_get('expedited_article_delivery_ill_url');
  $args = unserialize($_SESSION['open_url_fields']);
  
  foreach ($args as $key => $value) {
    $open_url = $open_url . $key . '=' . $value . '&';
  }
  
  $ill_link = $ill_link . $open_url;
  $variables['ill_link'] = $ill_link;
}

/**
 * Preprocess variables to be passed to the success page template assigned above in hook_theme().
 */
function template_preprocess_expedited_article_delivery_success_page(&$variables) {
  module_load_include('inc', 'expedited_article_delivery', 'includes/utilities');
  $order_info = expedited_article_delivery_success_processor($_GET); 
  $variables['order_id'] = $order_info['order_id'];
  $variables['rnd_id'] = $order_info['rnd_id'];
 }